apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-proxy-bouncer.fullname" . }}
  labels:
    {{- include "envoy-proxy-bouncer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.server.grpcPort | default (.Values.config.server.port | default .Values.service.port) }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.config.server.httpPort }}
    - port: {{ .Values.config.server.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "envoy-proxy-bouncer.selectorLabels" . | nindent 4 }}
