replicaCount: 1

image:
  repository: ghcr.io/kdwils/envoy-proxy-bouncer
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi

config:
  server:
    grpcPort: 8080
    httpPort: 8081
    logLevel: "info"

  trustedProxies: ["10.43.0.0/16", "10.42.0.0/16"]

  bouncer:
    enabled: true
    metrics: true
    lapiURL: "http://crowdsec-service:8080"
    tickerInterval: "10s"
    apiKeySecretRef:
      name: "envoy-bouncer"
      key: apiKey

  waf:
    enabled: true
    appSecURL: "http://crowdsec-appsec-service:7422"
    apiKeySecretRef:
      name: "envoy-bouncer"
      key: apiKey

  captcha:
    enabled: true # @schema default: false
    provider: "turnstile" # @schema default: ""
    siteKey: "0x4AAAAAAB1bbQbIpIhvAYwl" # @schema default: ""
    secretKey: "" # @schema default: ""
    secretKeySecretRef: # @schema type: object
      name: "envoy-bouncer" # @schema default: ""
      key: "secretKey" # @schema default: ""
    cacheDuration: "" # @schema default: ""
    hostname: "https://bouncer.int.kyledev.co" # @schema default: ""

securityPolicy:
  create: true
  gatewayName: "homelab"
  gatewayNamespace: "envoy-gateway-system"

autoscaling:
  enabled: false
